### PR TITLE
removing internal functions' examples

### PR DESCRIPTION
**Pull request by kartikeyakirar**
fixes: https://github.com/insightsengineering/teal.transform/issues/181

Note: 

- `resolve` methods are exported but generic is internal so here example of resolve is removed (resolve is used internally) 
- Earlier this was done to pre-release which has been reverted

### CODE REVIEW

**Comment by m7pr** [comment]
@kartikeyakirar can you export `resolve` generic?

**Comment by averissimo** [comment]
I don't think this is a good idea as it becomes very similar to `resolve_delayed`, the method that should be used in modules. (and wrapper around `resolve`).

Maybe we should leave it as it is for this release.

**Comment by kartikeyakirar** [comment]
> I don't think this is a good idea as it becomes very similar to resolve_delayed, the method that should be used in modules. (and wrapper around resolve).

I see your point. Since `resolve()` is used internal and in `resolve_delayed() `only, perhaps we should consider making all the methods exported also internal.

**Comment by m7pr** [comment]
So we do keep `resolve` unexported for now and then we rethinkg again : ) ?

**Review by m7pr — APPROVED** [review]
This is fine as it was reviewed already. This is now being merged to main, not pre-releaase

**Comment by averissimo** [comment]
I thought the discussion was still ongoing, we all find it weird, but it would be nice to have some context from @gogonzo as he reviewed it at the time.

https://github.com/insightsengineering/teal.transform/pull/76#discussion_r907530739

> We can unexport `resolve`. It will be just a S3 method called within `resolve_delayed`.
> 
> 
> `resolve_delayed` can have two variants `resolve_delayed.list(x, datasets, keys = attr(datasets, "join_keys")` and `resolve_delayed.FilteredData(x, datasets, keys = datasets$get_join_keys())`

**Comment by kartikeyakirar** [comment]
@averissimo We can continue this discussion on https://github.com/insightsengineering/coredev-tasks/issues/510. In this PR scope, we just wanted to remove the internal function example. In case we export the generic, we will update the reverted example and remove `getFromNamespace` (once reverted).

**Pull request merged**
