### PR TITLE
87 remove datasets - decrease package size

### PR DESCRIPTION
**Pull request by m7pr**
In the spirit of package size reduction https://github.com/insightsengineering/nestdevs-tasks/issues/87
I replaced all the calls for tmg datasets with their respective datasets from teal.data.
This way we no longer need to have datasets copies in tmg.

### CODE REVIEW

**Review by llrs-roche — CHANGES_REQUESTED** [review]
Looks good but I think you forgot to add `teal.data::` on test-data_extract_srv.R

**Comment by m7pr** [comment]
Ah, sorry for that! Looks like my substitutitions were limited just to `R` folder

**Comment by m7pr** [comment]
@llrs-roche would you revisit this PR?

**Review by llrs-roche — APPROVED** [review]

**Comment by llrs-roche** [comment]
Now all test passed locally too. Feel free to merge

**Pull request merged**
