### PR TITLE
218 Fixed failed pipeline

### LINKED ISSUE #218: Fix failed pipeline
https://github.com/pawelru/ie_status?tab=readme-ov-file

### PR DESCRIPTION
**Pull request by donyunardi**
Fixes #218

image

### CODE REVIEW

**Comment by donyunardi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by donyunardi** [comment]
Docs workflow is failing and I am able to reproduce it locally after installing the latest `evaluate` package

Here is the traces:

```r
r$> .Last.error
<callr_error/rlib_error_3_0/rlib_error/error>
Error: 
! in callr subprocess.
Caused by error in `build_reference()`:
! Failed to parse Rd in data_extract_multiple_srv.Rd
Caused by error in `is_call(x) && !is_call(x, "=") && !is_syntactic(x[[1]])`:
! 'length = 3' in coercion to 'logical(1)'
ℹ See `$stderr` for standard error.
---
Backtrace:
1. pkgdown::build_site()
2. pkgdown:::build_site_external(pkg = pkg, examples = examples, run_dont_run = run_dont_run, …
3. callr::r(function(..., cli_colors, hyperlinks, pkgdown_internet) { …
4. callr:::get_result(output = out, options)
5. callr:::throw(callr_remote_error(remerr, output), parent = fix_msg(remerr[[3]]))
---
Subprocess backtrace:
 1. pkgdown::build_site(...)
 2. pkgdown:::build_site_local(pkg = pkg, examples = examples, run_dont_run = run_dont_run, …
 3. pkgdown::build_reference(pkg, lazy = lazy, examples = examples, run_dont_run = run_dont_run, …
 4. pkgdown:::unwrap_purrr_error(purrr::map(topics, build_reference_topic, …
 5. base::withCallingHandlers(code, purrr_error_indexed = function(err) { …
 6. purrr::map(topics, build_reference_topic, pkg = pkg, lazy = lazy, …
 7. purrr:::map_("list", .x, .f, ..., .progress = .progress)
 8. purrr:::with_indexed_errors(i = i, names = names, error_call = .purrr_error_call, …
 9. base::withCallingHandlers(expr, error = function(cnd) { …
10. purrr:::call_with_cleanup(map_impl, environment(), .type, .progress, …
11. local .f(.x[[i]], ...)
12. base::withCallingHandlers(data_reference_topic(topic, pkg, examples_env = examples_env, …
13. pkgdown:::data_reference_topic(topic, pkg, examples_env = examples_env, …
14. pkgdown:::as_data(tags$tag_usage[[1]])
15. pkgdown:::as_data.tag_usage(tags$tag_usage[[1]])
16. base::vapply(parsed, needs_tweak, logical(1))
17. local FUN(X[[i]], ...)
18. base::.handleSimpleError(function (err) …
19. local h(simpleError(msg, call))
20. cli::cli_abort("Failed to parse Rd in {.file {topic$file_in}}", …
21. | rlang::abort(message, ..., call = call, use_cli_format = TRUE, …
22. | rlang:::signal_abort(cnd, .file)
23. | base::signalCondition(cnd)
24. (function (cnd) …
25. cli::cli_abort(message, location = i, name = name, parent = cnd, …
26. | rlang::abort(message, ..., call = call, use_cli_format = TRUE, …
27. | rlang:::signal_abort(cnd, .file)
28. | base::signalCondition(cnd)
29. (function (err) …
30. rlang::cnd_signal(err$parent)
31. rlang:::signal_abort(cnd)
32. base::signalCondition(cnd)
33. global (function (e) …
```

@insightsengineering/nest-core-dev any suggestion on what's going on?

<details>

<summary>SessionInfo()</summary>

```r
r$> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: x86_64-apple-darwin20
Running under: macOS Ventura 13.6.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5             cli_3.6.2               knitr_1.46              rlang_1.1.3             xfun_0.43              
 [6] processx_3.8.4          purrr_1.0.2             glue_1.7.0              htmltools_0.5.8.1       ps_1.7.6               
[11] fansi_1.0.6             rmarkdown_2.28          evaluate_0.24.0         tibble_3.2.1            fastmap_1.1.1          
[16] yaml_2.3.8              lifecycle_1.0.4         compiler_4.4.1          fs_1.6.4                nesttemplate_0.0.0.9008
[21] pkgconfig_2.0.3         digest_0.6.35           R6_2.5.1                utf8_1.2.4              pillar_1.9.0           
[26] callr_3.7.6             magrittr_2.0.3          tools_4.4.1             withr_3.0.1             pkgdown_2.1.0          
[31] desc_1.4.3
```

</details>

**Comment by donyunardi** [comment]
Found the problem, which is on line like this:
```
dataset_validation_rule = if (
                                    is.null(select_validation_rule) &&
                                      is.null(filter_validation_rule)
                                  ) {
                                    NULL
                                  } else {
                                    shinyvalidate::sv_required("Please select a dataset")
                                  },
```

Which we have [here](https://github.com/insightsengineering/teal.transform/blob/91b4026386f5c9a2ab6778217fcac27820cc23d2/R/data_extract_module.R#L738-L745) and [here](https://github.com/insightsengineering/teal.transform/blob/91b4026386f5c9a2ab6778217fcac27820cc23d2/R/data_extract_module.R#L738-L745).

If I temporarily set `dataset_validation_rule = NULL`, I'm able to build the site locally. 
Maybe there are some changes on the newer version of pkgdown.

**Comment by donyunardi** [comment]
@gogonzo 

Would it be a breaking change if I set `dataset_validation_rule = NULL` and move the logic to the function body?

```r

data_extract_multiple_srv.list <- function(data_extract,
                                           datasets,
                                           join_keys = NULL,
                                           select_validation_rule = NULL,
                                           filter_validation_rule = NULL,
                                           dataset_validation_rule = NULL, # setting it to NULL
                                           ...) {
  # move the logic to function's body
  if (is.null(dataset_validation_rule)) {
    if (!is.null(select_validation_rule) || !is.null(filter_validation_rule)) {
      dataset_validation_rule <- shinyvalidate::sv_required("Please select a dataset")
    }
  }
```

**Comment by gogonzo** [comment]
> Would it be a breaking change if I set dataset_validation_rule = NULL and move the logic to the function body?

No, unless somebody specified `dataset_validation_rule = NULL` somewhere already for some reason. I have completely no clue why `is.null()` in the condition doesn't work, but I've checked several solutions and this seems to work:

```r
dataset_validation_rule = if (
                                    length(select_validation_rule) || 
                                    length(filter_validation_rule)
                                  ) {
                                    shinyvalidate::sv_required("Please select a dataset")
                                  }
```

**Comment by pawelru** [comment]
That sounds familiar. Take a look at this: https://github.com/r-lib/pkgdown/issues/2727
Issue had been raised and resolved already. It's just not yet released.
To make it pass, I would recommend to use `extra-deps` workflow parameter (an example in `tern` [here](https://github.com/insightsengineering/tern/blob/afe9767025e94421779a15195c5a761ca110b7fc/.github/workflows/scheduled.yaml#L24-L25)). Please just make sure to annotate that it's temporary and link it to the issue / PR so that we can revert it once released without much investigation.

FYI: We have already done this for our docs workflow but not in the scheduled

**Comment by donyunardi** [comment]
> FYI: We have already done this for our docs workflow but not in the scheduled

The docs failure is not from the `Scheduled` workflow, but from the `Docs` workflow that I ran against this branch:
https://github.com/insightsengineering/teal.transform/actions/runs/10519469674/job/29147117999#step:12:175

image

`Scheduled` workflow is okay:
image

Do you think I can still use the solution that we did in tern for Docs workflow? 
if so, where should I add the `extra-deps` parameter?

**Comment by pawelru** [comment]
Oh sorry I was thinking you are referring to the scheduled one. I'm afraid that for the "docs" workflow there is no such parameter. There would be one in the future once we complete phase out of staged deps but this is not there yet. 

Let me ask @cicdguy for help. We chatted some time ago about this issue. Was it done? If not - what would be the best way to install dev version of pkgdown? Include in the image or install on the fly?

**Comment by m7pr** [comment]
I restarted the check to see if this is Docs failure is temporary or not https://github.com/insightsengineering/teal.transform/actions/runs/10591947450

**Comment by m7pr** [comment]
Hey @donyunardi just checking if the addition of `rmarkdown` to VignetteBuilder slot is the intentional change in here. 
`rmarkdown` engine is already included in `knitr` so there is no need to specify `rmarkdown` next to `knitr` in `VignetteBuilder`.
Have a look at `tidyr` package where they have the same scope of `rmarkdown` vignettes and `knitr` in DESCRIPTION https://github.com/tidyverse/tidyr/

**Comment by pawelru** [comment]
Hey @m7pr please have a look [here](https://github.com/insightsengineering/coredev-tasks/issues/577#issuecomment-2295842071) for resources why.

**Review by m7pr — APPROVED** [review]

**Pull request merged**
