### PR TITLE
update, replace scda by rcd in data raw

### LINKED ISSUE #219: replace scda use case by random.cdisc.data

### PR DESCRIPTION
**Pull request by shajoezhu**
close #219

### CODE REVIEW

**Comment by shajoezhu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Melkiades — APPROVED** [review]
Lgtm!! maybe we can take it out from dependencies too?

**Comment by shajoezhu** [comment]
> Lgtm!! maybe we can take it out from dependencies too?

hi @Melkiades, sorry, what do you mean, update the staged.deps file?

**Comment by Melkiades** [comment]
> > Lgtm!! maybe we can take it out from dependencies too?
> 
> hi @Melkiades, sorry, what do you mean, update the staged.deps file?

Do not mind, I checked and it is all good ;)

**Pull request merged**
